# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 491b8b651c3830ecfa49f7e919b4b17bb56b30a7f745840f8c4c0bf811331dc394652ad062342fccb8736e907c1f3518b2e0489d87c21ffab98d52a0a6069228

test:
  secret_key_base: 5920320afe715170db0d29a048f3d5a5f26a8650d4c9fbb280734de34fcdf774c10ebc1d38d32578003e89b9ac9a9d51d3577f34e0fe789869b181bb15c99cf8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
